### ISSUE TITLE
Is this meant to supersede / replace github.com/rickb777/date/period?

### ISSUE THREAD

**Issue by mihaitodor** [rickb777/period#1]
First of all, thank you for all the work you put into developing these packages! I imported it in [Benthos](https://github.com/benthosdev/benthos) to allow users to convert strings containing ISO8601 durations to nanoseconds and there's some interest in adding even more functionality, such as addition.

I noticed that you created this separate repo for the `period` subpackage and was wondering if the goal is to move the entire `period` package here. Should I consider switching to this one at a certain point?

**Comment by gavv** [comment]
Doubling the question.

https://pkg.go.dev/github.com/rickb777/date/period has this note:

> *** Warning: this package is the subject of many issues, so a replacement is under development. Please see https://github.com/rickb777/period. 

Could you please clarify what issues do you mean?

Thanks for your work!

**Comment by rickb777** [comment]
The existing Period code is overly complex, doesn't support weeks properly, has a quite limited numeric range and doesn't allow fields to have differing signs. Requests have been made to improve these issues.

BTW sorry this has taken so long to do.

**Comment by mihaitodor** [comment]
Good to know, thank you @rickb777! And thank you for working on this! Sounds like users should aim to migrate to `github.com/rickb777/period` eventually.

**Comment by rickb777** [comment]
I've merged in a PR and released v1.0.5 today.
